Bsi 178 tutorial
Babble-Stream-Integrations/babble3 pull request #31
Opened 2023-01-18 18:23 UTC by JarnoAkkerman

2023-01-19 20:58 UTC, sidvanvliet requested changes

2023-01-19 20:58 UTC, sidvanvliet commented on src/App.tsx
> +            session.platform === "youtube" ? " bg-youtube" : "bg-twitch"
This isn't future proof, as soon as we add TikTok for example, this will need to be changed

An improved version would be:

```
const platformClasses = {
    youtube: "border-youtube",
    twitch: "border-twitch",
}

// Then get the class with:
platformClasses[session.platform]
```

2023-01-19 20:58 UTC, sidvanvliet commented on src/App.tsx
> +            session.platform === "youtube" ? " border-youtube" : "border-twitch"
Same here

2023-01-19 20:58 UTC, sidvanvliet commented on src/components/playComponent/chat/youtubeViewCount.tsx
> +        setViewCount("0");
Might look better to not display view count at all until we've received data for it

2023-01-25 12:51 UTC, sidvanvliet approved these changes

2023-01-25 12:59 UTC, Lvdwardt approved these changes

2023-01-25 13:00 UTC, merged