Connected front-end with back-end
Babble-Stream-Integrations/babble3 pull request #4
Opened 2022-10-07 10:00 UTC by Lvdwardt

2022-10-07 10:09 UTC, sidvanvliet requested changes
Request changes as discussed on Discord

2022-10-07 10:21 UTC, sidvanvliet approved these changes

2022-10-07 10:47 UTC, sidvanvliet approved these changes

2022-10-10 07:44 UTC, srphihung approved these changes
beautiful code dude

2022-10-10 07:44 UTC, merged