Improved Login Flow
Babble-Stream-Integrations/babble3 pull request #43
Opened 2023-03-13 10:44 UTC by NexelOfficial

Implemented features
- Added Google login system which is now the users main account
- Added a way to link Twitch to the user account
- When logging in, the user no longer has to link Twitch
- Improved Cookies to work with just 1 cookie and JSON
- Added the new streamer homepage with streamer navbar

2023-03-13 12:01 UTC, Lvdwardt approved these changes

2023-03-13 13:31 UTC, Lvdwardt submitted a review, later dismissed

2023-03-16 08:29 UTC, sidvanvliet requested changes

2023-03-16 08:29 UTC, sidvanvliet commented on functions/package.json
> +    "@types/express": "^4.17.17",
Type definitions kan je onder devDependencies zetten, die zijn alleen relevant in de TypeScript development fase

2023-03-16 08:29 UTC, sidvanvliet commented on functions/src/controllers/authorization/YoutubeCallbackController.ts
> +          redirectUrl.searchParams.append("babbleToken", token.babbleToken);
🥰

2023-03-16 08:29 UTC, sidvanvliet commented on functions/src/index.ts
> +app.use(cors());
Is dit niet in essentie Allow All Origins voor CORS? Zo ja dan moeten we dit absoluut even alleen in development gebruiken hahaha

2023-03-16 08:29 UTC, sidvanvliet commented on functions/src/types.ts
> +};
Er is al een `types` directory :(

2023-03-16 08:30 UTC, sidvanvliet commented
Ziet er op uit macho @NexelOfficial, paar kleine changes gerequest, alleen maar kleine dingetjes maar 1 (CORS) is wel belangrijk om in ieder geval ff naar te kijken 

Thanks voor 't harde werk 🥰

2023-03-16 11:53 UTC, NexelOfficial commented on functions/src/index.ts
> +app.use(cors());
Dit is tijdelijk toegevoegd om een cors error op te lossen, maar doet in essentie al hetzelfde als hoe het nu in main werkt. ```res.append("Access-Control-Allow-Origin", ["*"]);```

2023-03-16 13:14 UTC, sidvanvliet commented on functions/src/index.ts
> +app.use(cors());
Ja dat het in main zit wilt natuurlijk niet zeggen dat het juist is, maar voor nu prima dan, kijken we een volgende sprint wel naar 👍, dan fixen we het gelijk project-wide

2023-03-16 13:16 UTC, sidvanvliet approved these changes

2023-03-16 13:17 UTC, Lvdwardt approved these changes

2023-03-16 13:17 UTC, merged